### ISSUE TITLE
Problema no CRUD do Atendente

### ISSUE THREAD

**Issue by Carlos-Henreis** [Carlos-Henreis/COM210Final#2]
Erro na INSERÇÃO do modelo atendente, quando atendente é inserido, o atributo password não é criptografado antes de ser persistido no banco. Ou seja, todo usuário Atendente inserido pelo ator presidente, não vão conseguir logar pois, na hora de autenticar a senha na tela de login não vai validar.
Isso deve ser selecionado alterando a view create do atendente (atendente/cruds/create.blade.php), além disso, existem alguns campos que ainda não estão validando os dados antes de inserir o mesmo problema pode ser selecionado, e também mostrar as mensagens de erros de inserção de dados errados pelo usuário (Ex: Tenta inserir um atendente que a chave primária já existe, etc)

**Comment by Samuel-Nicolai** [comment]
O problema da criptografia foi resolvido na Realise2, agora todos os usuários atendentes cadastrados conseguirão logar normalmente no sistema. O problema foi resolvido em atendentController.

**Comment by Samuel-Nicolai** [comment]
A validação dos dados no form também é feita.
