### ISSUE TITLE
Falha no carregamento da página ao tentar logar o Atendente

### ISSUE THREAD

**Issue by Sineek** [Carlos-Henreis/COM210Final#3]
Ao acessar a página do Atendente e ao preencher o e-mail e a senha, cadastrados anteriormente a página não carregou corretamente.

**Comment by Samuel-Nicolai** [comment]
Após a edição final do crud de atendente, foi retirado o comentário que impedia o carregamento correto da página. Modificação feita em Atendente/index.blade.php
