### ISSUE TITLE
Falha ao editar dados das entidades

### ISSUE THREAD

**Issue by Samuel-Nicolai** [Carlos-Henreis/COM210Final#4]
Ao editar os dados de alguma entidade (atendente, associado ou insumo), as regras de validação não permitem salvar os dados que não foram alterados, informando ao usuário erros de campos não preenchidos ou para os campos de chave primária, que os dados já existem no banco para um usuário.

**Comment by Sineek** [comment]
Insumo não apresenta tal problema. Acabo de testar Insumo e está funcionando, testei também o editar atendente e o problema realmente acontece.

**Comment by Carlos-Henreis** [comment]
Problemas resolvidos
